# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
  end

  #---------------------------------------------------------------------
  # SETUP ONLY
  config.vm.define :SETUP03 do |SETUP03|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.3", "setup"],
      keep_color: true,
      privileged: false
  end

  config.vm.define :SETUP04 do |SETUP04|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.4", "setup"],
      keep_color: true,
      privileged: false
  end

  #---------------------------------------------------------------------
  # ALL PACKAGES
  config.vm.define :ALL03 do |ALL03|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.3", "all"],
      keep_color: true,
      privileged: false
  end

  config.vm.define :ALL04 do |ALL04|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.4", "all"],
      keep_color: true,
      privileged: false
  end


  #---------------------------------------------------------------------
  # HALF PACKAGES
  config.vm.define :HALFAL03 do |HALFAL03|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.3", "AL"],
      keep_color: true,
      privileged: false
  end
  config.vm.define :HALFMZ03 do |HALFMZ03|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.3", "MZ"],
      keep_color: true,
      privileged: false
  end

  config.vm.define :HALFAL04 do |HALFAL04|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.4", "AL"],
      keep_color: true,
      privileged: false
  end
  config.vm.define :HALFMZ04 do |HALFMZ04|
    config.vm.provision :shell,
      path: "setup.sh",
      args: ["0.4", "MZ"],
      keep_color: true,
      privileged: false
  end

end
