# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :release do |release|
    config.vm.provision :shell, path: "setup.sh", args: ["release"], keep_color: true
  end

  config.vm.define :nightly do |nightly|
    config.vm.provision :shell, path: "setup.sh", args: ["nightly"], keep_color: true
  end
end
